bill_id = 101
customer_id = 1001
customer_name = "Rahul"
if_minor = False
bill_amount = 2000.50
print("Bill id = " , bill_id)
print("Customer id = " , customer_id)
print("Customer name =  " , customer_name)
print("Customer is a minor = " , if_minor )
print("Bill amount = " , bill_amount)